---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: apache24-bullseye64
    box: debian/bullseye64
  - name: apache24-buster64
    box: debian/buster64
lint: set -e; yamllint .; ansible-lint
provisioner:
  name: ansible
  become: true
