---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster64
    box: debian/buster64
    memory: 512
    cpus: 1
  - name: stretch64
    box: debian/stretch64
    memory: 512
    cpus: 1
lint: set -e; yamllint .; ansible-lint
provisioner:
  name: ansible
  become: true
