---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: apache24-bookworm64
    box: debian/bookworm64
provisioner:
  name: ansible
  become: true
  ansible_args:
    - --diff
lint: |
  set -e
  yamllint .
#  ansible-lint
